### ISSUE TITLE
Pid directory is beeing persisted

### ISSUE THREAD

**Issue by marcosfsch** [perfsonar/perfsonar-tools-docker#3]
I'm having some issues whenever a process crashes the pid files are being persisted through the container restart and I have to either manually remove the files or recreate the container to make it work. Is there a reason for creating a volume for /var/run?

My suggestion would be to use a tmpfs mount instead. Ex: docker run -d -P --net=host --tmpfs=/run perfsonar/tools

**Comment by arlake228** [comment]
As far as I can tell there is no reason to bind mount /var/run to the container at all, so I don't think we even need tmpfs.  I am unable to find a scenario where its needed beyond accessing docker from within your container - and in that case it should be /var/run/docker.sock. Our images don't need that though so I am not sure why that ended-up there. My guess is that either it used to be needed or got picked-up from an example with different requirements. Either way, it does not appear to be needed in the general case.
